// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Returns.Models.Data;

#nullable disable

namespace Returns.Migrations
{
    [DbContext(typeof(ReturnsDbContext))]
    [Migration("20250225135601_AddDddtionalDate")]
    partial class AddDddtionalDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Returns.Models.CamelSetup.CamelCategory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CamelCategories");
                });

            modelBuilder.Entity("Returns.Models.CamelSetup.CamelIndicator", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("BetterHigher")
                        .HasColumnType("bit");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CamelIndicators");
                });

            modelBuilder.Entity("Returns.Models.CamelSetup.IndicatorRatingThreshold", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IndicatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RatingLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("ThresholdValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IndicatorId");

                    b.ToTable("IndicatorRatingThresholds");
                });

            modelBuilder.Entity("Returns.Models.CapitalAdequacy", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CapitalGrantsEquityInNature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashLocalAndForeignCurrency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapitalToAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapitalToAssetsRatioExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapitalToDepositsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapitalToDepositsRatioExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositsAndBalancesAtOtherInstitutions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Difference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GeneralReserves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GovernmentSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstitutionalCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstitutionalCapitalToAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstitutionalCapitalToAssetsRatioExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Investments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsInSubsidiaryAndEquityInstruments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoansAndAdvances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumCoreCapitalToAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumCoreCapitalToDepositsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumInstitutionalToAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetSurplusAfterTaxCurrentYearToDate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherReserves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PropertyAndEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetainedEarningsAccumulatedLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ShareCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StatutoryReserves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SubTotalCoreCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAssetsPerBalanceSheet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDepositsLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOffBalanceSheetAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOnBalanceSheetAssets")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("CapitalAdequacies");
                });

            modelBuilder.Entity("Returns.Models.DepositReturn", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AmountInKshs000")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepositType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAccounts")
                        .HasColumnType("int");

                    b.Property<string>("RangeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("DepositReturns");
                });

            modelBuilder.Entity("Returns.Models.InvestmentReturn", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CoreCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinancialInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialInvestmentsToCoreCapitalExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialInvestmentsToCoreCapitalRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialInvestmentsToDepositsExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinancialInvestmentsToDepositsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LandAndBuildings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LandBuildingsRatioExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LandBuildingsToTotalAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxFinancialInvestmentsToCoreCapitalRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxFinancialInvestmentsToDepositsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxLandBuildingsToTotalAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaxNonEarningAssetsToTotalAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonEarningAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonEarningAssetsRatioExcessDeficiency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonEarningAssetsToTotalAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("InvestmentReturns");
                });

            modelBuilder.Entity("Returns.Models.LiquidityReturn", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BalancesDueToBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesDueToFinancialInstitutions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesDueToOtherFinancialInst")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesDueToOtherSaccoSocieties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesDueToSaccos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesWithCommercialBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesWithOtherFinancialInstitutions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesWithOtherSaccoSocieties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositsFromMembers")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepositsFromOtherSources")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ForeignNotesAndCoins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiabilitiesMaturing91Days")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiquidityRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiquidityRatioExcessDeficit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LocalNotesAndCoins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaturedLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaturedLoansFromFinancialInstitutions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinimumLiquidityRequirement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetBankBalances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetDepositLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetFinancialInstitutionBalances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetLiquidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OverdraftsAndMaturedLoans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TimeDepositsWithBanksMoreThan90Days")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalGovernmentSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNotesAndCoins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOtherLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalShortTermLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreasuryBills")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreasuryBonds")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("LiquidityReturns");
                });

            modelBuilder.Entity("Returns.Models.Period", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeadlineDay")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineMonth")
                        .HasColumnType("int");

                    b.Property<bool>("IsQuaterly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Returns.Models.QuarterDates", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeadlineDay")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineMonth")
                        .HasColumnType("int");

                    b.Property<int>("EndDay")
                        .HasColumnType("int");

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("QuarterDates");
                });

            modelBuilder.Entity("Returns.Models.Return", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnFor")
                        .HasColumnType("datetime2");

                    b.Property<string>("SaccoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Returns");
                });

            modelBuilder.Entity("Returns.Models.ReturnForm", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCapitalAdequencyForm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDepositReturnForm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinancialPosition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvestmentReturn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLiquidityStatement")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRiskClassification")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatementOfComprehensiveIncome")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaccoTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("ReturnForms");
                });

            modelBuilder.Entity("Returns.Models.RiskClassificationReturn", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfAccounts")
                        .HasColumnType("int");

                    b.Property<decimal?>("OutstandingLoanPortfolio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RequiredProvision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RequiredProvisionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("RiskClassifications");
                });

            modelBuilder.Entity("Returns.Models.SaccoAnalysis", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActionRequired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssetQualityRating")
                        .HasColumnType("int");

                    b.Property<int>("CapitalRating")
                        .HasColumnType("int");

                    b.Property<decimal>("ComplianceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ControlsScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CoreCapitalToAssetsRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EarningsRating")
                        .HasColumnType("int");

                    b.Property<decimal>("GovernanceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InstitutionalCapitalRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiquidAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LiquidityRating")
                        .HasColumnType("int");

                    b.Property<decimal>("LiquidityRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ManagementRating")
                        .HasColumnType("int");

                    b.Property<decimal>("NetIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonPerformingLoanRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonPerformingLoans")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ReturnOnAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLoans")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("SaccoAnalysis");
                });

            modelBuilder.Entity("Returns.Models.StatementOfComprehensiveIncomeReturn", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AdministrativeExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostOfExternalBorrowings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositsWithBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DepreciationAndAmortization")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividendExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Donations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FeesAndCommissionExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FeesAndCommissionOnLoanPortfolio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GovernanceExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GovernmentSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestExpenseOnDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestOnLoanPortfolio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MarketingExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonOperatingExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonOperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherFinancialExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherInvestments")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherOperatingIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PersonnelExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProvisionForLoanLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValueOfLoansRecovered")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("StatementOfComprehensiveIncomeReturns");
                });

            modelBuilder.Entity("Returns.Models.StatementOfFinancialPositionReturn", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AdjustmentToEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AllowanceForLoanLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalancesWithOtherSaccos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapitalGrants")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAtBank")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashInHand")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentYearSurplus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeferredTaxLiability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DividendsPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExternalBorrowings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GovernmentSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossLoanPortfolio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IntangibleAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentProperties")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InvestmentsInCompanies")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NonWithdrawableDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherLiabilities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherReserves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherSecurities")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaidLeaseRentals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrepaymentsAndSundryReceivables")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriorYearsRetainedEarnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PropertyAndEquipment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProposedDividends")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetirementBenefitAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RetirementBenefitsLiability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReturnId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("RevaluationReserves")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SavingsDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShareCapital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortTermDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StatutoryReserve")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPayable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxRecoverable")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReturnId");

                    b.ToTable("StatementOfFinancialPositionReturns");
                });

            modelBuilder.Entity("Returns.Models.CamelSetup.CamelIndicator", b =>
                {
                    b.HasOne("Returns.Models.CamelSetup.CamelCategory", "CamelCategory")
                        .WithMany("Indicators")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CamelCategory");
                });

            modelBuilder.Entity("Returns.Models.CamelSetup.IndicatorRatingThreshold", b =>
                {
                    b.HasOne("Returns.Models.CamelSetup.CamelIndicator", "CamelIndicator")
                        .WithMany("RatingThresholds")
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CamelIndicator");
                });

            modelBuilder.Entity("Returns.Models.CapitalAdequacy", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("CapitalAdequencies")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.DepositReturn", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("DepositReturns")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.InvestmentReturn", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("InvestmentReturns")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.LiquidityReturn", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("LiquidityReturns")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.QuarterDates", b =>
                {
                    b.HasOne("Returns.Models.Period", "Period")
                        .WithMany("QuarterDates")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Returns.Models.ReturnForm", b =>
                {
                    b.HasOne("Returns.Models.Period", "Period")
                        .WithMany("ReturnForms")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Returns.Models.RiskClassificationReturn", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("RiskClassifications")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.SaccoAnalysis", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("SaccoAnalysis")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.StatementOfComprehensiveIncomeReturn", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("StatementOfComprehensiveIncomeReturns")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.StatementOfFinancialPositionReturn", b =>
                {
                    b.HasOne("Returns.Models.Return", "Return")
                        .WithMany("StatementOfFinancialPositionReturns")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Return");
                });

            modelBuilder.Entity("Returns.Models.CamelSetup.CamelCategory", b =>
                {
                    b.Navigation("Indicators");
                });

            modelBuilder.Entity("Returns.Models.CamelSetup.CamelIndicator", b =>
                {
                    b.Navigation("RatingThresholds");
                });

            modelBuilder.Entity("Returns.Models.Period", b =>
                {
                    b.Navigation("QuarterDates");

                    b.Navigation("ReturnForms");
                });

            modelBuilder.Entity("Returns.Models.Return", b =>
                {
                    b.Navigation("CapitalAdequencies");

                    b.Navigation("DepositReturns");

                    b.Navigation("InvestmentReturns");

                    b.Navigation("LiquidityReturns");

                    b.Navigation("RiskClassifications");

                    b.Navigation("SaccoAnalysis");

                    b.Navigation("StatementOfComprehensiveIncomeReturns");

                    b.Navigation("StatementOfFinancialPositionReturns");
                });
#pragma warning restore 612, 618
        }
    }
}
