// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Returns.Models.Data;

#nullable disable

namespace Returns.Migrations
{
    [DbContext(typeof(ReturnsDbContext))]
    [Migration("20250224162905_FormsSetup")]
    partial class FormsSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Returns.Models.Period", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeadlineDay")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineMonth")
                        .HasColumnType("int");

                    b.Property<bool>("IsQuaterly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("Returns.Models.QuarterDates", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeadlineDay")
                        .HasColumnType("int");

                    b.Property<int>("DeadlineMonth")
                        .HasColumnType("int");

                    b.Property<int>("EndDay")
                        .HasColumnType("int");

                    b.Property<int>("EndMonth")
                        .HasColumnType("int");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<int>("StartMonth")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("QuarterDates");
                });

            modelBuilder.Entity("Returns.Models.ReturnForm", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCapitalAdequencyForm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDepositReturnForm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinancialPosition")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvestmentReturn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLiquidityStatement")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRiskClassification")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStatementOfComprehensiveIncome")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaccoTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("ReturnForms");
                });

            modelBuilder.Entity("Returns.Models.QuarterDates", b =>
                {
                    b.HasOne("Returns.Models.Period", "Period")
                        .WithMany("QuarterDates")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Returns.Models.ReturnForm", b =>
                {
                    b.HasOne("Returns.Models.Period", "Period")
                        .WithMany("ReturnForms")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Returns.Models.Period", b =>
                {
                    b.Navigation("QuarterDates");

                    b.Navigation("ReturnForms");
                });
#pragma warning restore 612, 618
        }
    }
}
